version: '3'
services:
  backend:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes: 
      - python-micro-django-dbdata:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  python-micro-django-dbdata:
